# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:450.0.0@sha256:4efe68502eacaaa5bbf77161c2bfd22004fac28ca45e4de02d4a45b0913f5887
RUN apt-get install -y netcat
