# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:452.0.0@sha256:f897f0db7d653e627637247d4defeecdfad6ccb49ffcd7063a5f8a98d95c807c
RUN apt-get install -y netcat
