# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:459.0.0@sha256:44b8d08fc6116cc53eb33aa213914714949f033023bdf2f606e1c46a1feeffc4
RUN apt-get install -y netcat
